In [21]:
import numpy as np

In [22]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
arr[3]

np.int64(14)

In [24]:
arr[1:5]

array([12, 13, 14, 15])

In [25]:
arr[2::]

array([13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
arr_slice = arr[2::2]
arr_slice

array([13, 15, 17, 19])

In [27]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [28]:
arr[0]

array([1, 2, 3, 4, 5])

In [29]:
arr[2,3]

np.int64(14)

In [30]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [31]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [32]:
arr[:,3]

array([ 4,  9, 14, 19, 24, 29])

In [33]:
bool_index = arr%2==0
bool_index

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [34]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [60]:
arr2 = np.arange(1,21)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [61]:
slice = arr2[:6]
slice

array([1, 2, 3, 4, 5, 6])

In [62]:
slice *10

array([10, 20, 30, 40, 50, 60])

In [63]:
slice = slice*10
slice

array([10, 20, 30, 40, 50, 60])

In [64]:
a= np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [65]:
b=a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [66]:
b[0]=99

In [67]:
b
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [68]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [69]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [77]:
c = b.copy()

In [81]:
c[0]=990

In [82]:
c

array([990,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [83]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])