In [32]:
import numpy as np

In [33]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [34]:
a=[1,2,3,54.2]
a

[1, 2, 3, 54.2]

In [35]:
np.array(a)

array([ 1. ,  2. ,  3. , 54.2])

In [36]:
m=[[1,2,3],[2,3,4],[3,4,6]]
m

[[1, 2, 3], [2, 3, 4], [3, 4, 6]]

In [37]:
np.array(m)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 6]])

In [38]:
arr =np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [39]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [40]:
arr = np.ones((4,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
arr = np.linspace(1,5,4)
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [42]:
np.random.rand(10)

array([0.7674043 , 0.02196074, 0.79720879, 0.53895941, 0.03224913,
       0.89769456, 0.0121099 , 0.64352601, 0.19937915, 0.64585366])

In [43]:
np.random.randint(10,20,10)

array([11, 15, 12, 10, 14, 14, 15, 17, 11, 10], dtype=int32)

In [44]:
arr = np.array([[1,23,4],[2,34,5],[34,56,7]])
arr

array([[ 1, 23,  4],
       [ 2, 34,  5],
       [34, 56,  7]])

In [45]:
arr.size

9

In [46]:
arr.dtype

dtype('int64')

In [47]:
arr.min()

np.int64(1)

In [48]:
arr.max()

np.int64(56)

In [49]:
arr.sum()

np.int64(166)

In [50]:
np.sum(arr,axis=1)

array([28, 41, 97])

In [51]:
arr.mean()

np.float64(18.444444444444443)

In [52]:
arr.std()

np.float64(18.288497363164343)

In [53]:
arr.argmax()

np.int64(7)

In [54]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [55]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])